# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tiny_recipe',
                'doc_host': 'https://radekosmulski.github.io',
                'git_url': 'https://github.com/radekosmulski/tiny_recipe',
                'lib_path': 'tiny_recipe'},
  'syms': {'tiny_recipe.core': {'tiny_recipe.core.foo': ('core.html#foo', 'tiny_recipe/core.py')}}}
